dist: trusty

language: go

go:
  - master # This uses automatically the latest version of go

env:
  global:
  - HUGO_VERSION=0.56.3  # set in the environment to make it easy

before_install:
- mkdir -p bin
- curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  -o bin/hugo.tar.gz
- tar xzvvf bin/hugo.tar.gz -C ./bin

script:
  - "./bin/hugo"

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master